#!/usr/bin/env python

import sys
import numpy as np
import pyfstat

f1 = sys.argv[1].rstrip('.par')
f2 = sys.argv[2].rstrip('.par')

params1 = pyfstat.read_par(f1, '.')
params2 = pyfstat.read_par(f2, '.')

for key in params1:
    if key+'_std' in params1: 
        v1 = params1[key]
        v1_std = params1[key+'_std']
        v2 = params2[key]
        v2_std = params2[key+'_std']
        diff = np.abs(v1 - v2)
        print key, diff/v1_std, diff/v2_std
