#!/usr/bin/python

"""

CLT to print labels and figure names in a latex document

"""

import argparse
from termcolor import colored
import glob
from collections import Counter
import numpy as np


def get_line_number(string, lines):
    split_lines = lines.split("\n")
    bools = [string in l for l in split_lines]
    idxs = [i for i, l in enumerate(split_lines) if string in l]
    return str(idxs[0]).ljust(5)


def print_elements(lines, file, splitter, alphabetic=False, containing="",
                   repeated_elements=""):
    parts = lines.split(splitter)
    elements = []
    for p in parts[1:]:
        elements.append(p[1+p.find("{"): p.find("}")])
    if alphabetic:
        elements = sorted(elements, key=lambda s: s.lower())

    count_of_repeated_elements = Counter(elements)

    if repeated_elements == "remove":
        elements = count_of_repeated_elements.keys()

    header = "Printing {} elements in {}:".format(splitter, file)
    print(colored(header, "red"))
    for f in elements:
        if containing in [None, "all"] or containing in f:
            ln = get_line_number(f, lines)
            f = "{}-> {}".format(ln, f)
            if repeated_elements == "highlight" and count_of_repeated_elements[f] > 1:
                print(colored(f, "blue", attrs=["underline"]))
            else:
                print(colored(f, "blue"))

parser = argparse.ArgumentParser(
    description="Print various quantities from .tex files")
parser.add_argument('--file', help="The tex file(s) to use", nargs=1)
parser.add_argument("-f", "--figures", action="store_true",
                    help="Print the figure names in the file")
parser.add_argument("-c", "--citations", action="store_true",
                    help="Print the citation keys in the file")
parser.add_argument("-l", "--label", const="all", nargs="?", type=str,
                    metavar="label_key",
                    help="""Print the \labels in the file. Optionally specify a
                    label_key such as `fig` in \label{fig: blah blah} to only
                    print the figure labels """)
parser.add_argument("-o", "--other", default=None,
                    help=("Print any arbitary latex element supplied after the"
                          " flag"))
parser.add_argument("-a", "--alphabetic", action="store_true",
                    help=("Print the results alphabetically"))
args = parser.parse_args()

# Getting the list of files and lines
files_list = []
lines_list = []
if args.file is None:
    # If no files supplied try and find some
    possible_files = glob.glob("*tex")
    for pf in possible_files:
        with open(pf) as f:
            lines = f.read()
        if "begin{document}" in lines:
            lines_list.append(lines)
            files_list.append(pf)
    if len(files_list) == 0:
        mssg = ("No files supplied and none found, are you in the right "
                "directory?")
        raise ValueError(colored(mssg, "red"))
else:
    for file in args.file:
        with open(file, "r") as f:
            lines_list.append(f.read())
            files_list.append(file)

if args.figures:
    for lines, file in zip(lines_list, files_list):
        print_elements(lines, file, splitter="includegraphics",
                       alphabetic=args.alphabetic,
                       repeated_elements="highlight")

if args.citations:
    for lines, file in zip(lines_list, files_list):
        print_elements(lines, file, splitter="cite",
                       repeated_elements="remove",
                       alphabetic=args.alphabetic)

if args.label:
    for lines, file in zip(lines_list, files_list):
        print_elements(lines, file, "label", alphabetic=args.alphabetic,
                       containing=args.label, repeated_elements="highlight")
if args.other:
    for lines, file in zip(lines_list, files_list):
        print_elements(lines, file, args.other, args.alphabetic)
